version: "3.8"
services:
  pg:
    image: postgres:15-bullseye
    command: sh -c "apt-get update && apt-get install -y postgresql-15-cron && docker-entrypoint.sh postgres -c 'max_connections=500' -c 'cron.database_name=$project_name_cabab_case$-dev' -c 'shared_preload_libraries=pg_cron'"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: $project_name_cabab_case$-dev
    restart: always
    volumes:
      - "./dump:/dump"
      - "./seeds:/seeds"
